name: app
description: Project template for Yefk
version: 2.0.0+2
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  connectivity_plus: ^6.1.1
  # facebook_app_events: ^0.19.4
  # firebase_analytics: ^11.3.6
  # firebase_core: ^3.9.0
  # firebase_crashlytics: ^4.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  flutter_web_plugins:
    sdk: flutter
  form_builder_extra_fields: ^11.1.0
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hancod_theme:
    path: ../themes/yefk_theme
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  # mobile_scanner: ^3.5.6
  path_provider: ^2.1.5
  pdf: ^3.11.1
  phone_form_field: 
  printing: ^5.13.4
  qr_code_scanner_plus: ^2.0.10+1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  scaled_app: ^2.3.0
  shared_preferences: ^2.3.4
  supabase_flutter: ^2.8.2
  timezone: ^0.10.0
  upgrader: ^11.3.1
  dotted_line: ^3.2.3
  url_launcher: ^6.2.5
  universal_html: ^2.0.15
  lottie: ^2.0.0
dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
